# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CourseSourcer' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift'
  pod 'RSKImageCropper'
  pod 'JSQMessagesViewController'
  pod 'Alamofire', '~> 3.4'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

  target 'CourseSourcerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CourseSourcerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
